### ISSUE TITLE
Install-AzureAutomationIseAddOn doesn't produce any output 

### ISSUE THREAD

**Issue by alexandair** [azureautomation/azure-automation-ise-addon#65]
It would be nice if Install-AzureAutomationIseAddOn emit an info that ISE profile script is modified; right now, it doesn't output anything. For example, add a support for -Verbose that will give us some info about the result of the cmdlet.

**Comment by JAL9302** [comment]
Done, has some verbose streams now.

**Comment by alexandair** [comment]
I still don't see any output when I run Install-AzureAutomationIseAddOn in 0.2.2.6.
