### ISSUE TITLE
PS Gallery doesn't put module in version path and causes Install-AzureAutomationIseAddOn to fail

### ISSUE THREAD

**Issue by elcooper** [azureautomation/azure-automation-ise-addon#71]
If download from PS Gallery doesn't put the module in a version path,  Install-AzureAutomationIseAddOn fails to find the module folder.

**Comment by JAL9302** [comment]
This should now be fixed.

**Comment by srinia** [comment]
This still fails for me. i.e.
PS C:\WINDOWS\system32> Install-Module AzureAutomationAuthoringToolkit
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Install-AzureAutomationIseAddOn
**Install-AzureAutomationIseAddOn : The term 'Install-AzureAutomationIseAddOn' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:1
- Install-AzureAutomationIseAddOn
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (Install-AzureAutomationIseAddOn:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException**

**Comment by JAL9302** [comment]
Where is Install-Module installing this module for you?

Also, according to the readme, please run:
`Install-Module AzureAutomationAuthoringToolkit -Scope CurrentUser`
Rather than
`Install-Module AzureAutomationAuthoringToolkit`

**Comment by srinia** [comment]
I tried both of these options. First ran it in CurrentUser scope. I am not sure where it is installing the module.

--Srini

**Comment by JAL9302** [comment]
Can you run Install-Module with -Verbose on and see where it says it puts the module?

**Comment by srinia** [comment]
Looks like it is getting installed at
VERBOSE: Module 'AzureAutomationAuthoringToolkit' was installed successfully to path '\cpzaw-pro-08\MyDocs3\srinia\My
Documents\WindowsPowerShell\Modules\AzureAutomationAuthoringToolkit\0.2.3.3'.

This is a shared folder in a network location and mapped to my “My Documents” folder.

--Srini

**Comment by JAL9302** [comment]
I'm not too familiar with how module loading works with regards to shares. If you do `Import-Module '\\cpzaw-pro-08\MyDocs3\srinia\My
Documents\WindowsPowerShell\Modules\AzureAutomationAuthoringToolkit'` does it load the module? Does `Install-AzureAutomationIseAddOn` then work?

**Comment by srinia** [comment]
Import worked after I specified the full directory including the version directory. i.e.

PS C:\Users\srinia> import-module '\cpzaw-pro-08\MyDocs3\srinia\My Documents\WindowsPowerShell\Modules\AzureAutomationAuthoringToolkit\0.2.3.3\AzureAutomationAuthoringToolkit'

thanks
--Srini
